environment_name: CartePole
nb_episodes_before_start: 5
seed: 13


dreamer:

  encoded_obs_size: 1024
  reccurent_size: 512
  latent_size: 30
  world_model_learning_rate: 2e-4
  actor_learning_rate      : 4e-5
  critic_learning_rate     : 1e-4

  encorder:
    depth: 16
    stride: 2
    padding: 1
    kernel_size: 3
    activation: ELU

  decorder:
    depth: 16
    stride: 2
    padding: 1
    kernel_size: 3
    activation: ELU

  recurrent_model:
    hidden_size: 400
    activation: ELU

  prior:
    hidden_size: 400
    nb_layers:   2
    activation:  ELU

  posterior:
    hidden_size: 400
    nb_layers:   2
    activation:  ELU

  reward_model:
    hidden_size: 400
    nb_layers: 2
    activation: ELU

  continuation:
    hidden_size: 400
    nb_layers: 3
    activation: ELU

  actor:
    hidden_size: 400
    nb_layers:   3
    activation:   ELU

  critic:
    hidden_size: 400
    nb_layers:   3
    activation:  ELU

  buffer:
    capacity: 50000