environment_name: CartPoleSwingUp
run_name: debug
seed: 13
device: mps

replay_ratio: 100
gradient_steps: 100000
checkpoint_interval: 1000
save_checkpoints: True
checkpoint_to_load: 57k
save_metrics: True

nb_episodes_before_start: 5
num_evaluation_episodes: 1
num_interaction_episodes: 1

dreamer:
  batch_size: 32
  batch_length: 64
  imagination_horizon: 16

  encoded_obs_size: 512
  recurrent_size: 200
  latent_size: 30
  use_continuation_prediction: False
  world_model_learning_rate: 0.0002
  actor_learning_rate      : 0.00004
  critic_learning_rate     : 0.0001
  discount: 0.99
  lambda_: 0.95
  gradient_norm_type: 2
  gradient_clip: 100

  entropy_scale: 0.0

  free_nats: 3.0
  kl_scale: 1.0
  pcont_scale: 10.0

  encoder:
    depth: 16
    stride: 2
    padding: 1
    kernel_size: 3
    activation: ELU

  decoder:
    depth: 16
    stride: 2
    padding: 1
    kernel_size: 3
    activation: ELU

  recurrent_model:
    hidden_size: 200
    activation: ELU

  prior:
    hidden_size: 200
    nb_layers:   2
    activation:  ELU

  posterior:
    hidden_size: 200
    nb_layers:   2
    activation:  ELU

  reward_model:
    hidden_size: 200
    nb_layers: 2
    activation: ELU

  continuation:
    hidden_size: 200
    nb_layers: 2
    activation: ELU

  actor:
    hidden_size: 200
    nb_layers: 2
    activation: ELU
    mean_scale: 5.0
    init_std: 5.0
    min_std: 0.0001

  critic:
    hidden_size: 200
    nb_layers: 2
    activation: ELU

  buffer:
    capacity: 50000


folder_names:
  metrics_folder: metrics
  plots_folder: plots
  checkpoints_folder: checkpoint
  videos_folder: videos
